---
- name: Copy file of database "cars" to /tmp
  ansible.builtin.copy:
    src: sql/cars.sql
    dest: /tmp/

- name: Create a new database with name "cars" and specific encoding and locale # settings
  community.postgresql.postgresql_db:
    name: cars
    encoding: UTF8
    lc_collate: ru_RU.UTF8
    lc_ctype: ru_RU.UTF8
    template: template0
    login_host: 10.10.10.254
    port: 5433
    login_user: "postgres"
    login_password: "zalando"

- name: Restore database using the tar format
  community.postgresql.postgresql_db:
    name: cars
    state: restore
    target: /tmp/cars.sql
    login_host: 10.10.10.254
    port: 5433
    login_user: "postgres"
    login_password: "zalando"